version: "3"
services:
        frontend:
                container_name: frontend
                build:
                        context: ./frontend
                        dockerfile: Dockerfile
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        - /home/ubuntu/ssl:/etc/nginx/certs
        backend:
                restart: always
                container_name: backend
                build: 
                        context: ./backend
                        dockerfile: Dockerfile
                expose:
                        - 5000
                        - 5050
                        - 5051
                        - 5052

